services:
  traefik:
    image: "traefik:v3.6"
    container_name: "paw-traefik"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./traefik/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    networks:
      - paw-apps-net

  dashboard:
    build: ./dashboard
    container_name: "paw-dashboard"
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./apps-code:/apps-code"
    environment:
      - BASE_DOMAIN=${BASE_DOMAIN}
    networks:
      - paw-mgmt-net
    depends_on:
      app-base:
        condition: service_completed_successfully

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: "paw-tunnel"
    restart: always
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - paw-mgmt-net

  app-base:
    build: ./app-base
    image: paw-user-app:latest
    container_name: paw-user-base
    command: "true"
    restart: "no"
    network_mode: "none"

networks:
  paw-mgmt-net:
    driver: bridge
    name: paw-mgmt-net
  paw-apps-net:
    driver: bridge
    name: paw-apps-net
