services:
  traefik:
    image: "traefik:v3.6"
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./traefik/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    networks:
      - web

  dashboard:
    build: ./dashboard
    container_name: "dashboard"
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./apps-code:/apps-code"
    environment:
      - BASE_DOMAIN=${BASE_DOMAIN}
    networks:
      - web

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: "tunnel"
    restart: always
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - web

networks:
  web:
    driver: bridge
    name: paw-web-network
